# Generated by Django 5.0.4 on 2024-07-18 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0, message='Total amount cannot be negative.')]),
        ),
    ]
