# Generated by Django 5.0.4 on 2024-07-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='facility_booking',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='facility_image',
            old_name='id',
            new_name='uuid',
        ),
    ]
