# Generated by Django 5.0.4 on 2024-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_rental', '0002_rename_id_amenity_uuid_rename_id_facility_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('workshop', 'Workshop'), ('art studio', 'Art Studio'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
