# Generated by Django 5.0.4 on 2024-07-17 12:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_rental', '0002_facility_booking_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Rating cannot be negative.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be more than five')])),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='facility_rental.facility_booking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility_rental.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
